// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwwwspwhrxgjtepewwcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3d3dzcHdocnhnanRlcGV3d2NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTUzNjQsImV4cCI6MjA2Nzc5MTM2NH0.ElLnLulmxaSw2pbR5WPOFZxfYKsENJIFhaML0B2L0nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});